version: "3"
services:
  api-database:
    image: mongo:4.2
    container_name: "api-database"
    ports:
      - 27017:27017
    volumes:
    - ./:/database
  api:
    image: ase-group-6:LATEST
    ports:
      - 8080:8080
    links:
      - api-database