spring:
  data:
    mongodb:
      database: Group6ASE
      host: localhost
      port: 27017
      #username: ADMIN
      #password: ASEG6ANKEET1

jwt:
  secret: ThisIsClearlyARandomSecret
  ExpirationMs: 86400000